filebeat.prospectors:
- input_type: log
paths:
- /var/log/vmware/sso/openidconnect.log
- /var/log/vmware/sso/vmware-rest-afd.log
- /var/log/vmware/sso/vmware-rest-idm.log
- /var/log/vmware/sso/vmware-rest-vmdir.log
multiline.pattern: '^\[[0-9]{4}-[0-9]{2}-[0-9]{2}'
multiline.negate: true
multiline.match: after
output.logstash:
hosts: ["@@LOGSTASH_ELB@@:5043"]